cakes/urls.py
from django.urls import path

from .views import *

app_name='cakes'

urlpatterns = [
    # Path to parse data from alenka.ru and save them into db
    path('parse/', parse, name='parse'),

    path('', index, name='index'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('catalog/', catalog, name='catalog'),

    path('profile/', profile, name='profile'),
    path('profile_update/', profile_update, name='profile_update'),

    path('cart_add/', cart_add, name='cart_add'),
    path('cart/', cart, name='cart'),
    path('cart_remove/', cart_remove, name='cart_remove'),
    path('cart_decrease/', cart_decrease, name='cart_decrease'),

    path("reminders/", reminders, name="reminders"),
    path("reminder/<int:id>", reminder, name="reminder"),
    path("create_reminder/", create_reminder, name="create_reminder"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('cakes.urls'))
]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cakes/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название',)
    price = models.IntegerField(verbose_name='Цена',)
    image = models.CharField(max_length=1024, verbose_name='Фотография',)
    amount = models.CharField(max_length=32, verbose_name='Вес/Количество',)
    category = models.CharField(max_length=255, verbose_name='Категория',)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return '%s %s' % (self.category, self.name)

cart/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings

from cakes.models import Product

class Cart:
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

    def add(self, product, quantity=1, update_quantity=False):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {'quantity': 0, 'price': str(product.price)}
        if update_quantity:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity
            self.save()

    def decrease(self, product, quantity=1):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {'quantity': 0, 'price': str(product.price)}
        else:
            self.cart[product_id]['quantity'] -= quantity
            self.save()

    def save(self):
        self.session[settings.CART_SESSION_ID] = self.cart
        self.session.modified = True

    def remove(self, product):
        product_id = str(product.id)
        if product_id in self.cart:
            del self.cart[product_id]
            self.save()

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())
    
    def clear(self):
        del self.session[settings.CART_SESSION_ID]
        self.session.modified = True

    def __iter__(self):
        product_ids = self.cart.keys()
        products = Product.objects.filter(id__in=product_ids)
        for product in products:
            self.cart[str(product.id)]['product'] = product

        for item in self.cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())
        

cakes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LogoutView
from django.contrib.auth.hashers import make_password
from django.views.decorators.http import require_POST
from cart.models import Cart

from users.models import *
from users.forms import *
from diary.models import *

from .models import *


def parse(request):
    from bs4 import BeautifulSoup
    import requests as r

    url = 'https://www.alenka.ru/catalog/'

    res = r.get(url)
    soup = BeautifulSoup(res.text, 'html.parser')
    products = soup.find_all('div', 's-card')

    for product in products:
        text = product.find('a', 's-card-body-title').text.split(' ')
        category = text[0]
        name = ''
        if 'гр' in text[-1]:
            name = ' '.join(text[1:-2])
        else:
            name = ' '.join(text[1:])
        name = name.replace(',', '')

        price, amount = product.find('span', 's-card-body-price-title-old-current').text.split()
        amount = amount.split('/')[1]
        image = 'https://www.alenka.ru' + product.find('img').attrs['data-src']
        data = {
        'name': name,
        'category': category,
        'price': price,
        'amount': amount,
        'image': image,
        }
        Product.objects.update_or_create(**data)
    return None

def index(request):
    return render(request, 'index.html')

class Logout(LogoutView):
    template_name = 'index.html'

def signin(request):
    if request.user.is_authenticated:
        return redirect('cakes:index')
    if request.method == 'GET':
        form = UserSigninForm()
        context = {'form': form}
        return render(request, 'signin.html', context)
    elif request.method == 'POST':
        form = UserSigninForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request,username=username,password=password)
            if user:
                login(request, user)
                return redirect('cakes:index')
            else:
                form = UserSigninForm()
                error = 'Неверные данные!'
                context = {'form': form, 'error': error}
                return render(request, 'signin.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('cakes:index')
    if request.method == 'GET':
        form = UserSignupForm()
        context = {'form': form}
        return render(request, 'signup.html', context)
    elif request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            password_confirm = form.cleaned_data['password_confirm']
            if password == password_confirm:
                User.objects.create(
                    username=username,
                    password=make_password(password),
                    first_name=name,
                    last_name=surname,
                    email=email
                )
                return redirect('cakes:signin')
            
def catalog(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, 'catalog.html', context)

def profile(request):
    if request.method == 'GET' and request.user.is_authenticated:
        context = {
            'user': request.user,
        }
        return render(request, 'profile.html', context)
    else:
        return redirect('cakes:index')
    
def profile_update(request):
    if request.method == 'GET' and request.user.is_authenticated:
        user = request.user
        context = {
            'user': user,
            'form': UserUpdateForm(instance=user),
        }
        return render(request, 'profile_update.html', context)
    elif request.method == 'POST' and request.user.is_authenticated:
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('cakes:profile')
        else:
            print(form.errors)
    else:
        return redirect('cakes:index')

@require_POST
def cart_add(request):
    cart = Cart(request)
    product = Product.objects.get(id=request.GET['id'])
    cart.add(product=product,
        quantity=1,
        update_quantity=False
    )
    return redirect(request.META.get('HTTP_REFERER'))

def cart(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart.html', context)

@require_POST
def cart_remove(request):
    cart = Cart(request)
    product = Product.objects.get(id=request.GET['id'])
    cart.remove(product)
    return redirect(request.META.get('HTTP_REFERER'))

@require_POST
def cart_decrease(request):
    cart = Cart(request)
    product = Product.objects.get(id=request.GET['id'])
    cart.decrease(product, 1)
    return redirect(request.META.get('HTTP_REFERER'))

def reminders(request):
    if request.method == 'PUT':
        attr = request.body.decode().split('&')
        id = int(attr[0].split('=')[1])
        checked = int(attr[1].split('=')[1])
        reminder = get_object_or_404(Reminders, id=id)
        reminder.checked = True if checked == 1 else False
        reminder.save()
    if request.GET.get('id'):
        if request.method == 'DELETE':
            id = int(request.GET.get('id'))
            get_object_or_404(Reminders, id=id).delete()
            return redirect('cakes:reminders')
        id = int(request.GET.get('id'))
        return render(request, 'reminder.html', {'reminder': get_object_or_404(Reminders, id=id)})
    return render(request, 'reminders.html', {'reminders': Reminders.objects.filter(user=request.user).order_by('-id')})


def reminder(request, id):
    if request.method == 'DELETE':
        get_object_or_404(Reminders, id=id).delete()
        return redirect('reminders')
    if request.method == 'POST':
        r = get_object_or_404(Reminders, id=id)
        r.text = request.POST['text']
        r.date = request.POST.get('time') if request.POST.get('time') else r.date
        r.save()
        return redirect('cakes:reminders')
    return render(request, 'reminder.html', {'reminder': get_object_or_404(Reminders, id=id)})

def create_reminder(request):
    if request.method == 'POST':
        data = request.POST
        reminder = Reminders()
        reminder.text = data['Text']
        reminder.user = request.user
        reminder.date = data['date']
        reminder.save()
        return redirect('cakes:reminders')
    elif request.method == 'DELETE':
        pass
    return render(request, 'create_reminder.html')

cart/views.py
from django.shortcuts import render

# Create your views here.

cakes/templates/cart.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="cart">

    {% for note in cart %}
        <div class="cartItem">
            <h1>
                {{ note.product.name }}
            </h1>
            <p class="categoryCart">
                {{ note.product.category }}
            </p>
            <div class="cartImageFunc">
                <img src="{{ note.product.image }}" />
                <div class="cartFunctionals">
                    <p>
                        Количество: {{ note.quantity }}
                    </p>
                    <div class="changeQuantity">
                        <form method="POST" action="{% url 'cakes:cart_decrease' %}?id={{ note.product.id }}">
                            {% csrf_token %}
                                <button class="minus" type="submit">
                                    -1
                                </button>
                        </form>
                        <form method="POST" action="{% url 'cakes:cart_add' %}?id={{ note.product.id }}">
                            {% csrf_token %}
                            <button class="quantity" type="submit">
                                +1
                            </button>
                        </form>
                    </div>
                    <form method="POST" action="{% url 'cakes:cart_remove' %}?id={{ note.product.id }}">
                        {% csrf_token %}
                            <button class="enter" type="submit">
                                Убрать из корзины
                            </button>
                    </form>
                    </div>
                </div>
            </div>
    {% endfor %}
 
</div>
{% endblock %}

cakes/templates/catalog.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="catalogPage">
    <div class="catSide">
        <div class="goods">Все товары</div>
        <div class="oneCat">
            <span class="catTitle">Конфеты</span>
            <div class="countCat">
                <span>1</span>
                <img class="arrowCat" src="{% static 'images/arrowWhite.svg'%}"/>
            </div>
        </div>
        <div class="oneCat">
            <span class="catTitle">Сливочные</span>
            <div class="countCat">
                <span>1</span>
                <img class="arrowCat" src="{% static 'images/arrowWhite.svg'%}"/>
            </div>
        </div>
        <div class="oneCat">
            <span class="catTitle">Халва</span>
            <div class="countCat">
                <span>1</span>
                <img class="arrowCat" src="{% static 'images/arrowWhite.svg'%}"/>
            </div>
        </div>
        <div class="oneCat">
            <span class="catTitle">Драже</span>
            <div class="countCat">
                <span>1</span>
                <img class="arrowCat" src="{% static 'images/arrowWhite.svg'%}"/>
            </div>
        </div>
        <div class="oneCat">
            <span class="catTitle">Батончик</span>
            <div class="countCat">
                <span>1</span>
                <img class="arrowCat" src="{% static 'images/arrowWhite.svg'%}"/>
            </div>
        </div>
    </div>
    <div class="catalogSide">
        <div class="catalogParams"> 
            <h1> Наши продукты </h1>
            <div class="sortBtn">
                <img src="{% static 'images/chart.svg' %}" />
                <span>По пулярности</span>
                <img src="{% static 'images/arrowTop.svg' %}"/>
            </div>
        </div>
        <div class="catalog">
            {% for product in products %}
                <div class="catalogCard">
                    <img src="{{ product.image }}" />
                    <h1>
                        {{ product.name }}
                    </h1>
                    <div class="infoCatalog">
                        <span class="category">
                            Категория: {{ product.category }}
                        </span>
                        <span class="price">
                            Цена: {{ product.price }} / {{ product.amount }}
                        </span>
                    </div>
                    <!-- CODE FOR CART -->
                    <form method="POST" action="{% url 'cakes:cart_add' %}?id={{ product.id }}">
                        {% csrf_token %}
                        <button class="corzina" type="submit">
                            <img class="corzinaImg" src="{% static 'images/telega.svg'%}" />
                        </button>
                    </form>
                    <!-- -->
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

cakes/templates/create_reminder.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/reminders.css' %}">
    <script src="{% static 'js/reminders.js' %}" defer></script>
    <form enctype="multipart/form-data" id="create_reminder" method="post" action="{% url 'cakes:create_reminder' %}" class="container">
        {% csrf_token %}
        <div class="mb-3">
            <label for="TextInput" class="form-label">Text</label>
            <input type="text" class="form-control" id="TextInput" name="Text"
                   value="" required>
        </div>
        <div class="mb-3">
            <label for="dateInput" class="form-label">date</label>
            <input type="datetime-local" class="form-control" id="dateInput" name="date" value=""
                   required>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" form="create_reminder" id="signInBtn">Создать</button>
        </div>
    </form>
{% endblock %}

cakes/templates/index.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    {% if request.user.is_authenticated %}
        АВТОРИЗОВАН
    {% endif %}
{% endblock content %}

cakes/templates/layout.html
{% load static %}
{% include 'navigation.html' %}


<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
    {% block navigation %}
    {% endblock navigation %}

    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>

cakes/templates/navigation.html
{% load static %}
<script src="{% static 'js/dropDown.js' %}"></script>
{% block navigation %}
<div class="navigation">
    <div class="navigationWrapper">
        <div class="navigationWrapperLogo">
            <h1>
                FIT & FOOD
            </h1>
        </div>
        <div class="navigationWrapperLinks">
            <ul class="navUl">
                <li>
                    <a href="{% url 'cakes:signin' %}"> Старт </a>
                </li>
                <li>
                    <a href="/catalog/"> Каталог </a>
                </li>
            </ul>
        </div>
        <div class="navigationWrapperProfile">
            <img src="{% static 'images/user.svg'%}" />
            <span>ПРОФИЛЬ</span>
            <img src="{% static 'images/dropdownArrow.svg'%}" />
            <div id="dropdownMenu" class="dropdownContent" style="display: none;">
                {% if request.user.is_authenticated %}
                    <a href="/profile/">Мой профиль</a>
                    <a href="{% url 'cakes:cart' %}">Корзина</a>
                    <a href="/catalog/">Конструктор тортов</a>
                    <a href="/catalog/">Отчёты</a>
                    <a href="{% url 'cakes:logout' %}">Выход</a>
                {% else %}
                    <a href="{% url 'cakes:signin' %}">Вход</a>
                    <a href="{% url 'cakes:signup' %}">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock navigation %}

cakes/templates/profile.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    <div class="profilePage">
        <div class="profileChar">
            {% if user.image %}
            <div 
                class="avatarWrapper"
                style="background-image: url('{{ user.image.url }}');"
            >
            </div>
            {% endif %}
            <h1 class="nickname">{{user.username}}</h1>
            <span class="profileMail">{{user.email}}</span>
            <span class="profileSpan">Тип учетной записи {{user.type}}</span>
            <span class="profileSpan"> имя: {{user.first_name}}</span>
            <span class="profileSpan"> фамилия: {{user.last_name}}</span>
            {% if user.adress %}
                <span class="profileSpan">{{user.adress}}<span>
            {% endif %}
        </div>
        <div class="profileFunctions">
            <a href="{% url 'cakes:profile_update' %}" class="profileBtn">Изменить профиль</a>
            <a href="/" class="profileBtn">Указать адрес</a>
            <a href="/" class="profileBtn">Фотоальбом</a>
            <a href="/" class="profileBtn">Написать в поддержку</a>
            <a href="{% url 'cakes:reminders' %}" class="profileBtn">Напоминания</a>
        </div>
    </div>
{% endblock %}

cakes/templates/profile_update.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="FormPage">
    <div class="signInUpTitle">Обновите данные</div>
            <form class="signInUpForm" method="POST">
                {% csrf_token %}
                <div class="signInUpFields">
                {% for field in form %}
                    <div class="updateFormField">
                        <span>{{ field.label }}</span> 
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="ifRdy">
                     <div class="signInUpButtons">
                        <button type="submit" class="enter">
                            Обновить данные
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

cakes/templates/reminder.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/reminders.css' %}">
    <script src="{% static 'js/reminders.js' %}" defer></script>
    <section class="container align-center">

        <div class="reminder">
            <form action="/reminder/{{ reminder.id }}" method="post">
            {% csrf_token %}
                <div class="form-check form-switch header-reminder">
                    <input id_reminder="{{ reminder.id }}" class="form-check-input check-js" type="checkbox"
                           id="flexSwitchCheckReverse" {% if reminder.checked %}checked{% endif %} name="checked">
                    <input class="form-check-label" for="flexSwitchCheckReverse" value="{{ reminder.text }}" name="text">
                </div>
                <input type="datetime-local" value="{{ reminder.date|date:'c' }}" name="time">
                <button class="btn btn-primary" type="submit">Обновить</button>
            </form>
        </div>


        <button class="btn btn-danger mb-2" id="qwertyuiopqwerty" id_reminder="{{ reminder.id }}">Удалить</button>

    </section>
{% endblock %}

cakes/templates/reminders.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/reminders.css' %}">
    <script src="{% static 'js/reminders.js' %}" defer></script>
    <section class="container align-center">
    <a href="{% url 'cakes:create_reminder' %}" class="btn btn-primary">Создать</a>
    {% for reminder in reminders %}
        <a class="reminder" href="/reminder/{{ reminder.id }}">
            <div class="form-check form-switch header-reminder">
                <input id_reminder="{{ reminder.id }}" class="form-check-input check-js" type="checkbox" id="flexSwitchCheckReverse" {% if reminder.checked %}checked{% endif %}>
                <label class="form-check-label" for="flexSwitchCheckReverse">{{ reminder.text }}</label>
            </div>
        <div>{{ reminder.date }}</div>
        </a>
    {% endfor %}
    </section>
{% endblock %}

cakes/templates/signin.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="formPage">
    <div class="signInUpTitle">Войдите в свой аккаунт</div>
    <form class="signInUpForm" method="POST">
        {% csrf_token %}
        <div class="signInUpFields">
        {% for field in form %}
            <div class="formField">
                <span>{{ field.label_tag }}</span> 
                {{ field }}
            </div>
        {% endfor %}
        </div>
        <div class="ifRdy">
            <div class="signInUpButtons">
                <button class="enter">
                    Войти
                </button>
                <button class="goToSignUpIn" method="GET" type="button" onclick="location.href='{% url 'cakes:signup' %}'">
                    Нет аккаунта?
                </button>
            </div>
        </div>
    </form>
</div>
<p>
    {{error}}
</p>
{% endblock content %}

cakes/templates/signup.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="FormPage">
    <div class="signInUpTitle">Создайте новый аккаунт</div>
    <form class="signInUpForm" method="POST">
        {% csrf_token %}
        <div class="signInUpFields">
        {% for field in form %}
            <div class="formField">
                <span>{{ field.label_tag }}</span> 
                {{ field }}
            </div>
        {% endfor %}
        </div>
        <div class="ifRdy">
            <div class="signInUpButtons">
                <button class="enter">
                    Зарегистрироваться
                </button>
                <button class="goToSignUpIn" method="GET" type="button" onclick="location.href='{% url 'cakes:signin' %}'">
                    Уже зарегистрированы?
                </button>
            </div>
        </div>
    </form>
</div>
<p>
    {{error}}
</p>
{% endblock content %}